create table if not exists entity (
    id                 bigint generated by default as identity primary key not null,
    entity_id          text                                                not null,
    entity_type        text                                                not null
);

create unique index if not exists entity_idx on entity (entity_id, entity_type);

create table if not exists comment
(
    id                 bigint generated by default as identity primary key not null,
    entity_ref_id      bigint                                              not null,
    text               text                                                not null,
    created_by         text                                                not null,
    created_at         timestamp with time zone default now()              not null,
    foreign key (entity_ref_id) references entity (id) on delete cascade
);

create index if not exists comment_idx on comment (entity_ref_id);