basePath: /v1
definitions:
  entity.Comment:
    properties:
      text:
        example: good
        type: string
      created_by:
        example: boss
        type: string
      entity_id:
        example: video_123
        type: string
      entity_type:
        example: video
        type: string
    type: object
  entity.CommentHistory:
    properties:
      history:
        items:
          $ref: '#/definitions/entity.Comment'
        type: array
    type: object
  request.Translate:
    properties:
      destination:
        example: en
        type: string
      original:
        example: текст для перевода
        type: string
      source:
        example: auto
        type: string
    required:
    - destination
    - original
    - source
    type: object
  response.Error:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a Comment service as an example
  title: Go Clean Template API
  version: "1.0"
paths:
  /comment/do-comment:
    post:
      consumes:
      - application/json
      description: Comment some entity
      operationId: do-comment
      parameters:
      - description: Set up comment
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Comment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Comment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Comment
      tags:
      - comment
  /comment/comments:
    get:
      consumes:
      - application/json
      description: Show all comments
      operationId: comments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.CommentHistory'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Show comments
      tags:
      - translation
swagger: "2.0"
