basePath: /v1
definitions:
  entity.Comment:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      entity_ref_id:
        type: integer
      text:
        type: string
    type: object
  entity.CommentsList:
    properties:
      comment:
        items:
          $ref: '#/definitions/entity.Comment'
        type: array
    type: object
  request.Comment:
    properties:
      created_by:
        example: user_kek
        type: string
      entity_id:
        example: shot_12
        type: string
      entity_type:
        example: shot
        type: string
      text:
        example: good job
        type: string
    required:
    - created_by
    - entity_id
    - entity_type
    - text
    type: object
  response.Error:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a comment service as an example
  title: Go Clean Template API
  version: "1.0"
paths:
  /comment/comments:
    get:
      consumes:
      - application/json
      description: Show all comments
      operationId: comments
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.CommentsList'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Show comments
      tags:
      - comment
  /comments/do-comment:
    post:
      consumes:
      - application/json
      description: Comment a entity
      operationId: do-comment
      parameters:
      - description: Set up comment
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Comment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Comment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Comment
      tags:
      - comment
swagger: "2.0"
